"""empty message

Revision ID: 231b33cb659a
Revises: 
Create Date: 2023-08-30 12:33:11.188679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '231b33cb659a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('addition_enabled', sa.Boolean(), nullable=False),
    sa.Column('addition_minimum', sa.Integer(), nullable=False),
    sa.Column('addition_maximum', sa.Integer(), nullable=False),
    sa.Column('subtraction_enabled', sa.Boolean(), nullable=False),
    sa.Column('subtraction_allow_negative', sa.Boolean(), nullable=False),
    sa.Column('subtraction_minimum', sa.Integer(), nullable=False),
    sa.Column('subtraction_maximum', sa.Integer(), nullable=False),
    sa.Column('multiplication_enabled', sa.Boolean(), nullable=False),
    sa.Column('multiplication_minimum', sa.Integer(), nullable=False),
    sa.Column('multiplication_maximum', sa.Integer(), nullable=False),
    sa.Column('division_enabled', sa.Boolean(), nullable=False),
    sa.Column('division_force_int', sa.Boolean(), nullable=False),
    sa.Column('division_dividend_minimum', sa.Integer(), nullable=False),
    sa.Column('division_dividend_maximum', sa.Integer(), nullable=False),
    sa.Column('division_divisor_minimum', sa.Integer(), nullable=False),
    sa.Column('division_divisor_maximum', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
